### ISSUE TITLE
Invalid options object

### ISSUE THREAD

**Issue by blin4504** [fullstack-hy2020/bloglist-frontend#5]
Getting this error when doing npm start: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema. I believe it might be an error with the proxy.

**Comment by sirbh** [comment]
@blin4504  were you able to solve it?

**Comment by sirbh** [comment]
> Getting this error when doing npm start: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema. I believe it might be an error with the proxy.

@blin4504 were you able to solve it?

**Comment by blin4504** [comment]
I haven't been able to solve it. I feel like the proxy thing should work.

**Comment by blin4504** [comment]
So after I deleted my re-pulled my backend from my github, added the env variables, and re-cloned the front-end, it worked.

**Comment by sirbh** [comment]
This worked instantly for me
https://stackoverflow.com/questions/70374005/invalid-options-object-dev-server-has-been-initialized-using-an-options-object
